
["Client Config"]
	#Change health display to a bar instead of hearts. Highly recommended. You can disable this if you want to use another mod for HUD, or you want half your screen taken up by little red hearts.
	"Change Health Display" = true
	#Remove vanilla armour display. With the changes this mod makes, the vanilla armour display is useless. This option is included if another mod you're using needs the armour level display event to function.
	"Remove Armour Display" = true
	#List of entities blacklisted from having their healthbar displayed. Takes
	#the registry name of a mob.
	"Blacklisted entities" = ["minecraft:example"]
	#Display mob's health bars only briefly (4 seconds) when they take damage.
	"Display only on damage" = false
	#How long to display mob's health bar when hit if the previous option is true.
	"Time in ticks" = 80

